# Generated by Django 4.2 on 2023-04-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe", models.TextField()),
                ("ingredient", models.TextField()),
                ("unit", models.TextField()),
                ("base_quantity", models.FloatField()),
                ("recipe_quantity", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="recipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient", models.TextField()),
                ("unit", models.TextField()),
                ("base_quantity", models.FloatField()),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="pybakery.recipes",
                        to_field="name",
                    ),
                ),
            ],
        ),
    ]
