# Generated by Django 4.2 on 2023-04-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybakery", "0002_recipes_image_alter_ingredients_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="recipes",
            new_name="Recipe",
        ),
    ]
