# Generated by Django 4.2 on 2023-04-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybakery", "0003_rename_recipes_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                height_field=250, upload_to="pybakery/static/pybakery", width_field=250
            ),
        ),
    ]
