# Generated by Django 4.2 on 2023-04-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybakery", "0004_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(upload_to="static/pybakery"),
        ),
    ]
