# Generated by Django 4.2 on 2023-04-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybakery", "0005_alter_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image_height",
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image_width",
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                height_field="image_height",
                upload_to="pybakery/static/pybakery",
                width_field="image_width",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
