# Generated by Django 4.2 on 2023-04-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybakery", "0006_recipe_image_height_recipe_image_width_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                height_field="image_height",
                upload_to="static/pybakery/",
                width_field="image_width",
            ),
        ),
    ]
