# Generated by Django 4.2 on 2023-04-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybakery", "0010_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                height_field="image_height",
                upload_to="images/",
                width_field="image_width",
            ),
        ),
    ]
