# Generated by Django 4.2 on 2023-04-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybakery", "0011_alter_recipe_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ingredients",
            new_name="Ingredient",
        ),
    ]
