# Generated by Django 4.2 on 2023-04-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybakery", "0012_rename_ingredients_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(max_length=250),
        ),
    ]
