# Generated by Django 4.2 on 2023-04-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybakery", "0013_alter_ingredient_ingredient_alter_ingredient_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="quantity",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
