# Generated by Django 4.2 on 2023-04-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybakery", "0014_basket_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basket",
            old_name="base_quantity",
            new_name="default_quantity",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="base_quantity",
            new_name="default_quantity",
        ),
    ]
