# Generated by Django 4.2 on 2023-04-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybakery", "0015_rename_base_quantity_basket_default_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basket",
            old_name="quantity",
            new_name="base_quantity",
        ),
        migrations.AddField(
            model_name="basket",
            name="base_unit",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
