# Generated by Django 4.2 on 2023-04-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybakery", "0016_rename_quantity_basket_base_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient", models.TextField()),
                ("quantity", models.FloatField()),
                ("unit", models.TextField()),
            ],
        ),
    ]
