# Generated by Django 4.2 on 2023-04-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybakery", "0017_calculation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculation",
            name="quantity",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
