# Generated by Django 4.2 on 2023-04-28 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybakery", "0019_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
